#!/usr/bin/env bash
#
# Shared setup for the local PHP backend. Sourced, not run.
#
# The handlers need four things a plain `vite` does not provide: PHP, a config
# with a secret, a writable directory for the counters and the guestbook, and a
# mailer that captures instead of sending. This puts all four in one place so
# scripts/dev.sh and scripts/php-test.sh cannot drift apart in how they set the
# backend up — the sort of difference that makes a suite pass while the browser
# fails, or the other way about.
#
# Everything it creates lives under frontend/.php-dev/, which is gitignored and
# can be deleted at any time; it is rebuilt on the next run.

# shellcheck disable=SC2034  # these are for the sourcing script

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLIC_DIR="$ROOT/frontend/public"
DEV_ROOT="$ROOT/frontend/.php-dev"

# The handler files, which is everything a web root needs to serve the API. The
# test run copies these into a root of its own rather than symlinking them: PHP
# resolves __DIR__ through a symlink to the real file's directory, so a
# symlinked contact.php would read the *dev* config and write to the dev
# guestbook — isolation that silently is not.
PHP_FILES=(
    form-lib.php
    contact.php
    guestbook.php
    guestbook-moderate.php
    contact-messages.json
    guestbook-messages.json
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# php_env_write_config <path> <rate_dir> <guestbook_dir> <site_url> [secret] [relax]
#
# Paths are written absolute. They are read at request time by a server whose
# working directory is not ours, and a relative path that resolves differently
# in the two is a bad afternoon.
#
# `relax` raises the hourly rate limits. Pass it for a dev session, where the
# guestbook's two-an-hour cap otherwise stops you after the second test message
# and there is nothing to do but wait. Do NOT pass it for a test run: the suites
# assert on the real caps.
php_env_write_config() {
    local path="$1" rate_dir="$2" gb_dir="$3" site_url="$4"
    local secret="${5:-$(php -r 'echo bin2hex(random_bytes(32));')}"
    local relax="${6:-}"
    local log_file="$DEV_ROOT/handler.log"

    local limits=""
    if [ -n "$relax" ]; then
        limits="
    /**
     * Raised so a dev session is not stopped by its own spam protection — the
     * guestbook's real cap is two an hour per address, which is two test
     * messages. The defaults are in the handlers; the config on the server
     * leaves these out entirely and gets them.
     *
     * High rather than absent: the counters still run, so the code path is
     * still exercised.
     */
    'contact_rate_limit' => 500,
    'contact_global_limit' => 1000,
    'guestbook_rate_limit' => 500,
    'guestbook_global_limit' => 1000,
"
    fi

    cat > "$path" <<EOF
<?php
/**
 * LOCAL DEV ONLY. Gitignored, generated by scripts/php-env.sh, and not the real
 * configuration — delete it and it is written again on the next run.
 *
 * The real one is uploaded to the server by hand and left there. See
 * contact-config.example.php for what every key means.
 */
declare(strict_types=1);

if (!defined('CONTACT_APP')) {
    http_response_code(403);
    exit;
}

return [
    'to' => 'dev@localhost',
    'from' => 'Website Contact <no-reply@localhost>',
    'secret' => '$secret',

    // Under frontend/.php-dev/, which is gitignored. On the server these have to
    // be somewhere a deploy does not overwrite — see contact-config.example.php.
    'rate_dir' => '$rate_dir',
    'guestbook_dir' => '$gb_dir',

    // Where the guestbook's delete links point. The Vite dev server, since that
    // is where you are looking at the app — the link then goes through the same
    // proxy the app's own requests do.
    'site_url' => '$site_url',

    'guestbook_enabled' => true,
    'enabled' => true,

    // One line per submission, and the reason whenever a store cannot be
    // reached. Worth having locally for the same reason it is worth having on
    // the server: it is what turns a one-word error into an answer.
    'log' => '$log_file',
$limits];
EOF
}

# An existing config may predate the guestbook. Say so plainly rather than
# letting the tab report itself unconfigured with no clue why.
php_env_check_config() {
    local path="$1"
    local gb
    gb="$(php -r '
        define("CONTACT_APP", true);
        $c = require $argv[1];
        echo is_array($c) ? (string) ($c["guestbook_dir"] ?? "") : "";
    ' "$path" 2>/dev/null)"

    if [ -z "$gb" ]; then
        echo
        echo "  !  $path has no 'guestbook_dir'."
        echo "     The guestbook tab will report itself unconfigured. Add:"
        echo
        echo "       'guestbook_dir' => '$DEV_ROOT/data',"
        echo
    fi

    # A config written before the limits were configurable will stop you after
    # two guestbook entries, which looks like a bug and is not.
    if ! grep -q "guestbook_rate_limit" "$path"; then
        echo
        echo "  !  $path has no raised rate limits, so the guestbook will refuse"
        echo "     a third entry in an hour. Delete the file to have it written"
        echo "     again, or add:"
        echo
        echo "       'guestbook_rate_limit' => 500,"
        echo "       'guestbook_global_limit' => 1000,"
        echo
    fi
}

# Where the handlers are actually reading and writing, resolved from the config
# rather than assumed — so the two can never disagree in the output.
php_env_report() {
    local path="$1" mail_log="$2"
    php -r '
        define("CONTACT_APP", true);
        $c = require $argv[1];
        $dir = fn($k) => ($c[$k] ?? null) ? (realpath($c[$k]) ?: $c[$k]) : "(unset)";
        printf("  entries   %s\n", $dir("guestbook_dir"));
        printf("  counters  %s\n", $dir("rate_dir"));
        printf("  mail to   %s\n", $c["to"] ?? "(unset)");
    ' "$path" 2>/dev/null || true
    echo "  mail log  $mail_log"
}

# ---------------------------------------------------------------------------
# The capturing mailer
# ---------------------------------------------------------------------------

# php_env_write_sendmail <path> <log>
#
# mail() hands the whole message — headers and body — to this on stdin, so the
# log is exactly what would have been sent. That matters more than it sounds for
# the guestbook: the delete link exists nowhere else, so a stub that discarded
# the message would leave moderation with no way to be reached or tested.
php_env_write_sendmail() {
    local path="$1" log="$2"
    cat > "$path" <<EOF
#!/bin/sh
{
  echo "----- \$(date -u +%Y-%m-%dT%H:%M:%SZ) -----"
  cat
  echo
} >> "$log"
EOF
    chmod +x "$path"
}

# ---------------------------------------------------------------------------
# The server
# ---------------------------------------------------------------------------

# php -S prints "Address already in use" and exits, but by then the caller has
# already announced a port — so requests quietly go to whatever was listening,
# with the previous config and the previous maildir, and nothing points at
# either. Refuse instead.
php_env_require_port() {
    local port="$1"
    if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
        echo "port $port is already in use — stop that server first:" >&2
        lsof -nP -iTCP:"$port" -sTCP:LISTEN >&2
        return 1
    fi
}

# php_env_stop <pid> <port>
#
# **Only ever call this with a pid this script started.** The port sweep below
# kills whatever is listening, so calling it on the strength of the port alone
# takes down somebody else's server. That is not hypothetical: the exit trap ran
# unconditionally at first, so a second `npm run dev` — refused the port because
# one was already running — killed the running instance's backend on its way
# out, and left a dev session with a proxy answering 503 and no clue why.
#
# Killing the pid alone is not enough either. PHP_CLI_SERVER_WORKERS makes php -S
# fork workers, and they do not go with the parent — they keep the socket, so
# the next run is refused a port nothing appears to own. Kill the parent, then
# anything still holding the port.
php_env_stop() {
    local pid="${1:-}" port="${2:-}"

    # No pid means we never got as far as starting one, so there is nothing of
    # ours to stop and the port belongs to someone else.
    [ -n "$pid" ] || return 0

    kill "$pid" 2>/dev/null || true

    if [ -n "$port" ]; then
        local strays
        strays="$(lsof -nP -iTCP:"$port" -sTCP:LISTEN -t 2>/dev/null || true)"
        # shellcheck disable=SC2086  # deliberately word-split: one pid per line
        [ -n "$strays" ] && kill $strays 2>/dev/null || true
    fi
    return 0
}

# php_env_serve <port> <doc_root> <sendmail> <log_file>
#
# Sets PHP_PID. Binds 127.0.0.1 explicitly: binding to :: makes `curl localhost`
# succeed while a browser fails, which is a miserable hour.
#
# PHP_CLI_SERVER_WORKERS is not optional. php -S is serial by default, and the
# locking the rate limits depend on is never actually contended without it — so
# the concurrency checks pass whatever the code does.
php_env_serve() {
    local port="$1" doc_root="$2" sendmail="$3" log="$4"

    # opcache off. It caches the *compiled* contact-config.php and only
    # revalidates every couple of seconds by default, so an edit to the config
    # does not take effect on the next request — which is confusing while
    # developing and made a test silently pass against a config it had just
    # changed. Nothing here is slow enough to want the cache.
    PHP_CLI_SERVER_WORKERS=8 php \
        -d sendmail_path="$sendmail" \
        -d display_errors=0 \
        -d opcache.enable=0 \
        -S "127.0.0.1:$port" \
        -t "$doc_root" >"$log" 2>&1 &
    PHP_PID=$!

    # Wait for it to answer rather than sleeping a fixed guess
    local n=0
    until curl -fsS -o /dev/null "http://127.0.0.1:$port/contact.php" 2>/dev/null; do
        n=$((n + 1))
        if [ "$n" -gt 80 ] || ! kill -0 "$PHP_PID" 2>/dev/null; then
            echo "the PHP server did not start — see $log" >&2
            cat "$log" >&2
            return 1
        fi
        sleep 0.25
    done
}
